"""create relation between the user and the services to know who add them

Revision ID: 29274205d845
Revises: eeff14d2938d
Create Date: 2026-09-20 21:24:22.685714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29274205d845'
down_revision: Union[str, Sequence[str], None] = 'eeff14d2938d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'created_by')
    # ### end Alembic commands ###
