"""add customer role

Revision ID: 4a4981dcd79f
Revises: 0a7a604eef5d
Create Date: 2026-09-14 17:20:58.227720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4981dcd79f'
down_revision: Union[str, Sequence[str], None] = '0a7a604eef5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'customer' ")
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
