"""change the name of the relation to rour schedules and also gave a default value for the status 

Revision ID: bc61f983c1dc
Revises: 5d6de4dc3d5a
Create Date: 2026-09-27 16:32:51.651301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc61f983c1dc'
down_revision: Union[str, Sequence[str], None] = '5d6de4dc3d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
